apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: integration-service-leader-election-rolebinding
  namespace: integration-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: integration-service-leader-election-role
subjects:
- kind: ServiceAccount
  name: integration-service-controller-manager
  namespace: integration-service
