apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: delete-snapshots
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - snapshots
  verbs:
  - delete
  - deletecollection
