apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: integration-service-snapshot-garbage-collector
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - releases
  - snapshotenvironmentbindings
  verbs:
  - get
  - list
- apiGroups:
  - appstudio.redhat.com
  resources:
  - snapshots
  verbs:
  - get
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
