apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: build-service-manager-rolebinding
  namespace: build-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: build-service-manager-role
subjects:
- kind: ServiceAccount
  name: build-service-controller-manager
  namespace: build-service
