apiVersion: v1
kind: ConfigMap
metadata:
  name: build-pipeline-config
  namespace: build-service
data:
  config.yaml: |
    default-pipeline-name: docker-build
    pipelines:
    - name: fbc-builder
      bundle: quay.io/redhat-appstudio-tekton-catalog/pipeline-fbc-builder:668382ea32335cecf67d89953b59f27ab994f3c7
    - name: docker-build
      bundle: quay.io/redhat-appstudio-tekton-catalog/pipeline-docker-build:668382ea32335cecf67d89953b59f27ab994f3c7
