apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - admissionregistration.k8s.io_v1_mutatingwebhookconfiguration_release-service-mutating-webhook-configuration.yaml
  - admissionregistration.k8s.io_v1_validatingwebhookconfiguration_release-service-validating-webhook-configuration.yaml
  - apiextensions.k8s.io_v1_customresourcedefinition_releaseplanadmissions.appstudio.redhat.com.yaml
  - apiextensions.k8s.io_v1_customresourcedefinition_releaseplans.appstudio.redhat.com.yaml
  - apiextensions.k8s.io_v1_customresourcedefinition_releases.appstudio.redhat.com.yaml
  - apiextensions.k8s.io_v1_customresourcedefinition_releaseserviceconfigs.appstudio.redhat.com.yaml
  - apps_v1_deployment_release-service-controller-manager.yaml
  - batch_v1_cronjob_remove-expired-releases.yaml
  - rbac.authorization.k8s.io_v1_clusterrolebinding_release-service-application-role-binding.yaml
  - rbac.authorization.k8s.io_v1_clusterrolebinding_release-service-component-role-binding.yaml
  - rbac.authorization.k8s.io_v1_clusterrolebinding_release-service-environment-role-binding.yaml
  - rbac.authorization.k8s.io_v1_clusterrolebinding_release-service-manager-rolebinding.yaml
  - rbac.authorization.k8s.io_v1_clusterrolebinding_release-service-proxy-rolebinding.yaml
  - rbac.authorization.k8s.io_v1_clusterrolebinding_release-service-releaseplanadmission-role-binding.yaml
  - rbac.authorization.k8s.io_v1_clusterrolebinding_release-service-releaseplan-role-binding.yaml
  - rbac.authorization.k8s.io_v1_clusterrolebinding_release-service-release-role-binding.yaml
  - rbac.authorization.k8s.io_v1_clusterrolebinding_release-service-snapshotenvironmentbinding-role-binding.yaml
  - rbac.authorization.k8s.io_v1_clusterrolebinding_release-service-snapshot-role-binding.yaml
  - rbac.authorization.k8s.io_v1_clusterrolebinding_release-service-tekton-role-binding.yaml
  - rbac.authorization.k8s.io_v1_clusterrole_release-pipeline-resource-role.yaml
  - rbac.authorization.k8s.io_v1_clusterrole_release-service-application-role.yaml
  - rbac.authorization.k8s.io_v1_clusterrole_release-service-component-role.yaml
  - rbac.authorization.k8s.io_v1_clusterrole_releaseserviceconfig-role.yaml
  - rbac.authorization.k8s.io_v1_clusterrole_release-service-environment-viewer-role.yaml
  - rbac.authorization.k8s.io_v1_clusterrole_release-service-manager-role.yaml
  - rbac.authorization.k8s.io_v1_clusterrole_release-service-proxy-role.yaml
  - rbac.authorization.k8s.io_v1_clusterrole_release-service-release-editor-role.yaml
  - rbac.authorization.k8s.io_v1_clusterrole_release-service-releaseplanadmission-editor-role.yaml
  - rbac.authorization.k8s.io_v1_clusterrole_release-service-releaseplanadmission-viewer-role.yaml
  - rbac.authorization.k8s.io_v1_clusterrole_release-service-releaseplan-editor-role.yaml
  - rbac.authorization.k8s.io_v1_clusterrole_release-service-releaseplan-viewer-role.yaml
  - rbac.authorization.k8s.io_v1_clusterrole_release-service-release-viewer-role.yaml
  - rbac.authorization.k8s.io_v1_clusterrole_release-service-snapshot-editor-role.yaml
  - rbac.authorization.k8s.io_v1_clusterrole_release-service-snapshotenvironmentbinding-editor-role.yaml
  - rbac.authorization.k8s.io_v1_clusterrole_release-service-snapshot-viewer-role.yaml
  - rbac.authorization.k8s.io_v1_clusterrole_release-service-tekton-role.yaml
  - rbac.authorization.k8s.io_v1_rolebinding_releaseserviceconfigs-rolebinding.yaml
  - rbac.authorization.k8s.io_v1_rolebinding_release-service-leader-election-rolebinding.yaml
  - rbac.authorization.k8s.io_v1_role_release-service-leader-election-role.yaml
  - v1_configmap_release-service-manager-config.yaml
  - v1_configmap_release-service-manager-properties.yaml
  - v1_namespace_release-service.yaml
  - v1_serviceaccount_release-service-controller-manager.yaml
  - v1_service_release-service-controller-manager-metrics-service.yaml
  - v1_service_release-service-webhook-service.yaml
  - release-service-config.yaml
  - https://github.com/redhat-appstudio/internal-services/config/crd?ref=7edcb7e47f44c002edb94ad6c6ff70e7930f3dfc
