apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: releaseserviceconfigs-rolebinding
  namespace: release-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: releaseserviceconfig-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
