apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: release-service-releaseplanadmission-viewer-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - releaseplanadmissions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - releaseplanadmissions/status
  verbs:
  - get
