apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: releaseserviceconfig-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - releaseserviceconfigs
  verbs:
  - get
  - list
  - watch
