apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: release-service-application-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-service-application-role
subjects:
- kind: ServiceAccount
  name: release-service-controller-manager
  namespace: release-service
