apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-service-leader-election-rolebinding
  namespace: release-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-service-leader-election-role
subjects:
- kind: ServiceAccount
  name: release-service-controller-manager
  namespace: release-service
