apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: integration-service-prometheus-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: integration-service-prometheus-viewer-role
subjects:
- kind: ServiceAccount
  name: integration-service-metrics-reader
  namespace: integration-service
