apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: image-controller-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: image-controller-proxy-role
subjects:
- kind: ServiceAccount
  name: image-controller-controller-manager
  namespace: image-controller
