apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: image-controller
  namespace: image-controller
spec:
  endpoints:
  - bearerTokenSecret:
      key: token
      name: metrics-reader
    interval: 15s
    path: /metrics
    port: https
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      control-plane: controller-manager
