apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-image-controller-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: image-controller-metrics-reader
subjects:
- kind: ServiceAccount
  name: metrics-reader
  namespace: image-controller
