apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: build-service-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
