apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    kubernetes.io/service-account.name: metrics-reader
  name: metrics-reader
  namespace: build-service
type: kubernetes.io/service-account-token
